ServerEvents.recipes(event => {

event.remove({ output: 'ironchest:trapped_dirt_chest' })
event.remove({ output: 'ironchest:trapped_obsidian_chest' })
event.remove({ output: 'ironchest:trapped_crystal_chest' })
event.remove({ output: 'ironchest:gold_to_diamond_chest_upgrade' })
event.remove({ output: 'ironchest:diamond_to_obsidian_chest_upgrade' })
event.remove({ output: 'ironchest:diamond_to_crystal_chest_upgrade' })
event.remove({ output: 'ironchest:dirt_chest' })
event.remove({ output: 'ironchest:diamond_chest' })
event.remove({ output: 'ironchest:obsidian_chest' })
event.remove({ output: 'ironchest:crystal_chest' })
event.remove({ output: 'trials:crafter' })
event.remove({ output: 'create:schematic_table' })
event.remove({ output: 'create:schematic_and_quill' })
event.remove({ output: 'create:empty_schematic' })
event.remove({ output: 'farmersdelight:rope' })
event.remove({ output: 'endermanoverhaul:corrupted_shield' })
event.remove({ output: 'create:schematicannon' })
event.remove({ id: 'backpacked:backpack' })
event.remove({ id: 'farmersdelight:safety_net' })

})